# Generated by Django 3.2.12 on 2024-01-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, null=True)),
                ('key_skills', models.TextField(default=None, null=True)),
                ('salary_from', models.IntegerField(default=None, null=True)),
                ('salary_to', models.IntegerField(default=None, null=True)),
                ('salary_currency', models.CharField(default=None, max_length=10, null=True)),
                ('area_name', models.TextField(default=None, null=True)),
                ('published_at', models.DateTimeField(default=None)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancies',
            },
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
