# Generated by Django 3.2.12 on 2024-01-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, null=True)),
                ('salary', models.IntegerField(default=None, null=True)),
                ('area_name', models.TextField(default=None, null=True)),
                ('published_at', models.DateTimeField(default=None)),
            ],
            options={
                'verbose_name': 'Обработанная вакансия',
                'verbose_name_plural': 'Обработанные вакансии',
                'db_table': 'processed_vacancies',
            },
        ),
    ]
