# Generated by Django 3.2.12 on 2024-01-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_processedvacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgSalaryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('average_salary', models.FloatField()),
            ],
            options={
                'verbose_name': 'Статистика по средней зарплате',
                'verbose_name_plural': 'Статистика по средней зарплате',
                'db_table': 'avg_salary_stats',
            },
        ),
        migrations.CreateModel(
            name='BackendAvgSalaryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('backend_average_salary', models.FloatField()),
            ],
            options={
                'verbose_name': 'Статистика по средней зарплате Backend-программистов',
                'verbose_name_plural': 'Статистика по средней зарплате Backend-программистов',
                'db_table': 'backend_avg_salary_stats',
            },
        ),
        migrations.CreateModel(
            name='BackendStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('backend_vacancy_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Статистика по Backend-программистам',
                'verbose_name_plural': 'Статистика по Backend-программистам',
                'db_table': 'backend_stats',
            },
        ),
        migrations.CreateModel(
            name='VacancyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('vacancy_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Статистика по количеству вакансий',
                'verbose_name_plural': 'Статистика по количеству вакансий',
                'db_table': 'vacancy_stats',
            },
        ),
    ]
