# Generated by Django 3.2.12 on 2024-01-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_avgsalarystats_backendavgsalarystats_backendstats_vacancystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='DolyaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('vacancy_percentage', models.FloatField()),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам',
                'verbose_name_plural': 'Доля вакансий по городам',
                'db_table': 'dolya_area',
            },
        ),
        migrations.CreateModel(
            name='DolyaAreaBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('vacancy_percentage', models.FloatField()),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам для бэкендера',
                'verbose_name_plural': 'Доля вакансий по городам для бэкендера',
                'db_table': 'dolya_area_backend',
            },
        ),
        migrations.CreateModel(
            name='SalaryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('average_salary', models.FloatField()),
            ],
            options={
                'verbose_name': 'Уровень зарплат по городам',
                'verbose_name_plural': 'Уровень зарплат по городам',
                'db_table': 'salary_area',
            },
        ),
        migrations.CreateModel(
            name='SalaryAreaBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('average_salary', models.FloatField()),
            ],
            options={
                'verbose_name': 'Уровень зарплат по городам для бэкендера',
                'verbose_name_plural': 'Уровень зарплат по городам для бэкендера',
                'db_table': 'salary_area_backend',
            },
        ),
    ]
